import 'package:lingogame/constants/keyboardKeyState.dart';

Map<String, KeyboardKeyState> keysMap = {
  'E': KeyboardKeyState.knotAnswered,
  'R': KeyboardKeyState.knotAnswered,
  'T': KeyboardKeyState.knotAnswered,
  'Y': KeyboardKeyState.knotAnswered,
  'U': KeyboardKeyState.knotAnswered,
  'I': KeyboardKeyState.knotAnswered,
  'O': KeyboardKeyState.knotAnswered,
  'P': KeyboardKeyState.knotAnswered,
  'Ğ': KeyboardKeyState.knotAnswered,
  'Ü': KeyboardKeyState.knotAnswered,
  'A': KeyboardKeyState.knotAnswered,
  'S': KeyboardKeyState.knotAnswered,
  'D': KeyboardKeyState.knotAnswered,
  'F': KeyboardKeyState.knotAnswered,
  'G': KeyboardKeyState.knotAnswered,
  'H': KeyboardKeyState.knotAnswered,
  'J': KeyboardKeyState.knotAnswered,
  'K': KeyboardKeyState.knotAnswered,
  'L': KeyboardKeyState.knotAnswered,
  'Ş': KeyboardKeyState.knotAnswered,
  'İ': KeyboardKeyState.knotAnswered,
  'ENTER': KeyboardKeyState.knotAnswered,
  'Z': KeyboardKeyState.knotAnswered,
  'C': KeyboardKeyState.knotAnswered,
  'V': KeyboardKeyState.knotAnswered,
  'B': KeyboardKeyState.knotAnswered,
  'N': KeyboardKeyState.knotAnswered,
  'M': KeyboardKeyState.knotAnswered,
  'Ö': KeyboardKeyState.knotAnswered,
  'Ç': KeyboardKeyState.knotAnswered,
  'BACK': KeyboardKeyState.knotAnswered,
};
